apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jobtree-system
helmCharts:
  - name: gpu-fleet
    releaseName: jobtree
    chartHome: ../helm
    valuesFile: values-prod.yaml
