apiVersion: v1
kind: Service
metadata:
  name: {{ include "gpu-fleet.controllerName" . }}
  labels: {{- include "gpu-fleet.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "gpu-fleet.controllerName" . }}
  ports:
    - name: metrics
      port: {{ .Values.controller.metricsPort }}
      targetPort: metrics
{{- if .Values.monitoring.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gpu-fleet.controllerName" . }}
  labels: {{- include "gpu-fleet.labels" . | nindent 4 }}
  {{- if .Values.monitoring.serviceMonitorNamespace }}
  namespace: {{ .Values.monitoring.serviceMonitorNamespace }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gpu-fleet.controllerName" . }}
  endpoints:
    - port: metrics
      interval: {{ .Values.monitoring.scrapeInterval }}
{{- end }}
